// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_HGrMtoo51_zo3XEu0IVB3fE14ydfb0k',
    appId: '1:149339775076:web:caf6ea7b0f969f90ffff71',
    messagingSenderId: '149339775076',
    projectId: 'fluxtecapp',
    authDomain: 'fluxtecapp.firebaseapp.com',
    databaseURL: 'https://fluxtecapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fluxtecapp.appspot.com',
    measurementId: 'G-C94VVZ678G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgMMLBIFPHDvoUcACcwQm5sqv47vrjEA',
    appId: '1:149339775076:android:6eab588dbff2044affff71',
    messagingSenderId: '149339775076',
    projectId: 'fluxtecapp',
    databaseURL: 'https://fluxtecapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fluxtecapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvntzW-OJKXeveOBeptikZz42RdrA58IM',
    appId: '1:149339775076:ios:bb437696c9a05b62ffff71',
    messagingSenderId: '149339775076',
    projectId: 'fluxtecapp',
    databaseURL: 'https://fluxtecapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fluxtecapp.appspot.com',
    iosBundleId: 'com.example.terraTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvntzW-OJKXeveOBeptikZz42RdrA58IM',
    appId: '1:149339775076:ios:bb437696c9a05b62ffff71',
    messagingSenderId: '149339775076',
    projectId: 'fluxtecapp',
    databaseURL: 'https://fluxtecapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fluxtecapp.appspot.com',
    iosBundleId: 'com.example.terraTrace',
  );
}
