name: terratrace
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.0+17

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_crashlytics: ^4.2.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  flutter_spinkit: ^5.2.1
  csv: ^6.0.0
  watcher: ^1.1.1
  flutter_local_notifications: ^18.0.1
  rflutter_alert: ^2.0.7
  go_router: ^14.6.2
  flutter_riverpod: ^2.6.1
  internet_connection_checker: ^3.0.1
  flutter_map_heatmap: ^0.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  riverpod: ^2.6.1
  sliding_up_panel2: ^3.3.0+1
  fl_chart: ^0.70.1
  geolocator: ^13.0.2
  # flutter_blue: ^0.8.0
  flutter_blue_plus: ^1.34.5
  shared_preferences: ^2.3.5
  syncfusion_flutter_charts: ^28.1.39
  sliding_up_panel: ^2.0.0+1
  # google_maps_flutter: ^2.10.0
  utm: ^0.1.3-nullsafety.1
  mapbox_maps_flutter: ^2.6.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  share_plus: ^10.1.4
  syncfusion_flutter_datagrid: ^28.2.11
  # flutter_map_marker_popup: ^7.0.0
  # flutter_reactive_ble: ^5.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - images/
  - assets/.env
  - assets/mbus.json

  fonts:
  - family: Barlow
    fonts:
      - asset: fonts/Barlow-Light.ttf
  - family: BarlowLight
    fonts:
      - asset: fonts/Barlow-ExtraLight.ttf
  - family: BarlowThin
    fonts:
      - asset: fonts/Barlow-Thin.ttf

  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
