// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-BNOi_qQz36y9WzSeFIec58PubVD5kh4',
    appId: '1:230653883435:web:49a0ae3efce159f587266e',
    messagingSenderId: '230653883435',
    projectId: 'terratrace-1555e',
    authDomain: 'terratrace-1555e.firebaseapp.com',
    storageBucket: 'terratrace-1555e.firebasestorage.app',
    measurementId: 'G-X459WN3YBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYiKSCHJSeWiKKdeOb0h6re9Mhl_0ATRs',
    appId: '1:230653883435:android:b47ea6d51ece750287266e',
    messagingSenderId: '230653883435',
    projectId: 'terratrace-1555e',
    storageBucket: 'terratrace-1555e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUUUU4XrP3GiE4UP5PDt0D4_TIfXKclHs',
    appId: '1:230653883435:ios:8341934508c88f9b87266e',
    messagingSenderId: '230653883435',
    projectId: 'terratrace-1555e',
    storageBucket: 'terratrace-1555e.firebasestorage.app',
    iosBundleId: 'ai.terratrace.terratrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUUUU4XrP3GiE4UP5PDt0D4_TIfXKclHs',
    appId: '1:230653883435:ios:8341934508c88f9b87266e',
    messagingSenderId: '230653883435',
    projectId: 'terratrace-1555e',
    storageBucket: 'terratrace-1555e.firebasestorage.app',
    iosBundleId: 'ai.terratrace.terratrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-BNOi_qQz36y9WzSeFIec58PubVD5kh4',
    appId: '1:230653883435:web:b4d460046c3fce3487266e',
    messagingSenderId: '230653883435',
    projectId: 'terratrace-1555e',
    authDomain: 'terratrace-1555e.firebaseapp.com',
    storageBucket: 'terratrace-1555e.firebasestorage.app',
    measurementId: 'G-NDZC9EGZHY',
  );
}
